### PR TITLE
Fix folders

### LINKED ISSUE #43: grafanaDashboardFolder field does not work
Currently on `v0.0.1`, this field seems to always get ignored. Simplest way to reproduce is adding it to the dashboard in `testdata`, and `grr apply` it:

```
{
  grafanaDashboardFolder: 'FOO',
  grafanaDashboards+:: {
    'my-dash.json': {
      uid: 'prod-overview',
      title: 'Production Overview',
      tags: ['templated'],
      timezone: 'browser',
      schemaVersion: 16,
    },
  },
}
```

The dashboard will be created in _*General*_, and _*FOO*_ will be ignored

### PR DESCRIPTION
**Pull request by malcolmholmes**
Starts from #42 , and pushes it a bit further. This will create a folder if it does not yet exist, and also makes sure that changing a folder results in a re-apply.

Closes #42, closes #43 .

### CODE REVIEW

File: pkg/grizzly/grafana.go [hunk 1]
```diff
@@ -124,38 +125,76 @@ func (b Board) GetDashboardJSON() (string, error) {
...
+func (f *Folder) toJSON() (string, error) {
+	j, err := json.MarshalIndent(f, "", "  ")
+	if err != nil {
+		return "", err
+	}
+	return string(j), nil
+}
+
+func getFolder(config Config, UID string) (int64, error) {
+	if UID == "0" {
```
Comment (Duologic) [inline pkg/grizzly/grafana.go:138]: Does this mean the General folder?

File: pkg/grizzly/grafana.go [hunk 2]
```diff
@@ -191,13 +230,18 @@ func getDashboard(config Config, uid string) (*Board, error) {
 
 	type nestedBoard struct {
 		Dashboard Board `json:"dashboard"`
+		Meta      struct {
+			FolderID    int64  `json:"folderId"`
+			FolderTitle string `json:"folderTitle"`
+		} `json:"meta"`
 	}
+
```
Comment (Duologic) [inline pkg/grizzly/grafana.go:238]: Can you drop a comment here on why it is nested? (I think I introduced this but apparently it is less clear as I thought it would be).

**Review by Duologic — APPROVED** [review]
LGTM, comments are more for further understanding the code.

File: pkg/grizzly/grafana.go (hunk 1 above)
Comment (malcolmholmes) [reply pkg/grizzly/grafana.go:138]: yep, the default one.

File: pkg/grizzly/grafana.go (hunk 2 above)
Comment (malcolmholmes) [reply pkg/grizzly/grafana.go:238]: that's just how the JSON comes back from the API.

**Review by Duologic — APPROVED** [review]
