### PR TITLE
Check for nil folder UID

### LINKED ISSUE #263: "grr get DashboardFolder." leads to unmarshall error
Trying to export a list of folders from the server, and it cannot unmarshall. Output below was redacted.

```
$ grr get DashboardFolder.
INFO[0000] Getting DashboardFolder.                     
FATA[0000] Error retrieving dashboard folder : Failed to parse Grafana response: json: cannot unmarshal array into Go value of type grafana.Folder.

Response:
[{"id":n,"uid":"x","title":"x"},...,{"id":n,"uid":"x","title":"x"}]
```

### PR DESCRIPTION
**Pull request by malcolmholmes**
Closes #263﻿

### CODE REVIEW

File: pkg/grafana/folder-handler.go [hunk 1]
```diff
@@ -151,6 +151,9 @@ func (h *FolderHandler) getRemoteFolder(uid string) (*grizzly.Resource, error) {
 		if err != nil {
 			return nil, err
 		}
+		if uid == "" {
```
Comment (julienduchesne) [inline pkg/grafana/folder-handler.go:154]: Should be the very first condition of the function IMO

Comment (malcolmholmes) [reply pkg/grafana/folder-handler.go:154]: fair. Moved.

**Review by julienduchesne — APPROVED** [review]
