### PR TITLE
Correctly create configuration files when none already exists

### LINKED ISSUE #377: [Bug]: cannot config using grr config set
### Grizzly Version

0.4.0

### Expected Behavior

expect to config grafana URL etc as showing on documentation

grr config set grafana.url http://localhost:3000

### Actual Behavior

 cannot config using grr config set, got FATA error:

[root@st1lnpansible02 bin]# grr config set grafana.url http://10.5.32.38:3000
FATA[0000] open : no such file or directory   

Using strace showing it's trying to open a empty file:

$ strace -eopen,openat grr config set grafana.url
http://localhost:3000/
 
openat(AT_FDCWD, "/sys/kernel/mm/transparent_hugepage/hpage_pmd_size", O_RDONLY) = 3
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
openat(AT_FDCWD, "/usr/local/bin/grr", O_RDONLY|O_CLOEXEC) = 3
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
openat(AT_FDCWD, "/etc/localtime", O_RDONLY) = 3
openat(AT_FDCWD, "", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
FATA[0000] open : no such file or directory             
+++ exited with 1 +++

### Steps to Reproduce

run the config set command:
grr config set grafana.url http://localhost:3000

### PR DESCRIPTION
**Pull request by K-Phoen**
Fixes #377

Grizzly failed identifying where it should write its configuration when no configuration file existed in any of the expected locations.

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -207,13 +209,21 @@ func CreateContext(name string) error {
 
 func Write() error {
 	err := viper.WriteConfig()
-	if err != nil {
-		if _, ok := err.(viper.ConfigFileNotFoundError); ok {
-			configpath := viper.ConfigFileUsed()
```
Comment (K-Phoen) [inline pkg/config/config.go:212]: This returns an empty string, since no config file was used.

**Review by malcolmholmes — APPROVED** [review]
